accounts/urls.py
from django.contrib.auth.views import (
    LoginView, LogoutView, PasswordResetView,
    PasswordResetConfirmView, PasswordChangeView, PasswordResetDoneView
)
from accounts.forms import UserPasswordResetForm, UserPasswordResetConfirmForm, UserPasswordChangeForm, UserLoginForm
from accounts.views import UserProfileView, activate, UserRegistrationView, UserUpdateView, UserDeleteView
from django.urls import path
from companies.views import CompanyListView, CompanyCreateView, CompanyUpdateView, CompanyDeleteView
from managers.views import ManagerListView

app_name = 'accounts'

urlpatterns = [
    path('login/',
         LoginView.as_view(
             template_name='registration/login.html',
             authentication_form=UserLoginForm),
         name='login'),

    path('logout/',
         LogoutView.as_view(
             template_name='registration/logout.html'),
         name='logout'),

    path('password_reset/',
         PasswordResetView.as_view(
             template_name='registration/password_reset_form.html',
             form_class=UserPasswordResetForm,),
         name='password_reset'),

    path('password_reset_confirm/<uidb64>/<token>',
         PasswordResetConfirmView.as_view(
             template_name='registration/password_reset_confirm.html',
             form_class=UserPasswordResetConfirmForm),
         name='password_reset_confirm'),

    path('password_change/',
         PasswordChangeView.as_view(
             template_name="registration/password_change_form.html",
             form_class=UserPasswordChangeForm),
         name='password_change'),

    path('activate/<uidb64>/<token>/', activate, name='activate'),
    path('registration/', UserRegistrationView.as_view(), name='registration'),

    path('profile/', UserProfileView.as_view(), name='profile'),
    path('profile/update/<int:pk>/', UserUpdateView.as_view(), name='profile-update'),
    path('profile/delete/<int:pk>/', UserDeleteView.as_view(), name='profile-delete'),

    path('profile/companies/', CompanyListView.as_view(), name='companies'),
    path('profile/managers/', ManagerListView.as_view(template_name='managers/manager_list.html'), name='managers'),
    path('profile/companies/add/', CompanyCreateView.as_view(), name='companies-add'),
    path('profile/companies/update/<slug:slug>/', CompanyUpdateView.as_view(), name='companies-update'),
    path('profile/companies/delete/<slug:slug>/', CompanyDeleteView.as_view(), name='companies-delete'),
]

companies/urls.py
from django.urls import path, include

from companies.views import CompanyDetailView

app_name = 'companies'

urlpatterns = [
    path('', CompanyDetailView.as_view(), name='dashboard'),
    path('managers/', include('managers.urls', namespace='managers')),
    path('products/', include('products.urls', namespace='products')),
    path('customers/', include('customers.urls', namespace='customers')),
    path('orders/', include('orders.urls', namespace='orders')),
]

contacts/urls.py
from django.urls import path

from contacts.views import (
    ContactDeleteView,
    ContactCreateView,
    ContactUpdateView,
    ContactHistoryCreate,
    ContactHistoryDelete,
    ContactHistoryUpdate
)

app_name = 'contacts'

urlpatterns = [
    path('add/', ContactCreateView.as_view(), name='add'),
    path('update/<int:pk_contact>/', ContactUpdateView.as_view(), name='update'),
    path('delete/<int:pk_contact>/', ContactDeleteView.as_view(), name='delete'),

    path('add-history/', ContactHistoryCreate.as_view(), name='add-history'),
    path('update-history/<int:pk_contact_history>/', ContactHistoryUpdate.as_view(), name='update-history'),
    path('delete-history/<int:pk_contact_history>/', ContactHistoryDelete.as_view(), name='delete-history'),
]

core/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.contrib.staticfiles.storage import staticfiles_storage
from django.urls import path, include
from django.views.generic import RedirectView

from core.views import LandingView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('<slug:slug>/', include('companies.urls', namespace='companies')),
    path('', LandingView.as_view(), name='landing'),
    path(
        'favicon.ico',
        RedirectView.as_view(url=staticfiles_storage.url('favicon.ico')),
    ),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

customers/urls.py
from django.urls import path, include

from customers.views import (
    CustomerListView,
    CustomerCreateView,
    CustomerDeleteView,
    CustomerUpdateView,
    CustomerDetailView,

    remove_preferred_product,
)

app_name = 'customers'

urlpatterns = [
    path('', CustomerListView.as_view(), name='customers'),
    path('add/', CustomerCreateView.as_view(), name='add'),
    path('<int:pk>/', CustomerDetailView.as_view(), name='detail'),
    path('update/<int:pk>/', CustomerUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', CustomerDeleteView.as_view(), name='delete'),

    path('<int:pk>/contacts/', include('contacts.urls', namespace='contacts')),

    path('<int:pk>/preferred-products/remove/<int:pk_product>/', remove_preferred_product,
         name='remove-preferred-product'),
]

orders/urls.py
from django.urls import path

from orders.views import (
    OrderListView,
    OrderCreateView,
    OrderDeleteView,
    OrderItemCreateView,
    OrderItemDeleteView,
    orders_charts,
)

app_name = 'orders'

urlpatterns = [
    path('', OrderListView.as_view(), name='orders'),
    path('add/', OrderCreateView.as_view(), name='add'),
    path('delete/<int:pk>', OrderDeleteView.as_view(), name='delete'),
    path('<int:pk>/add-item', OrderItemCreateView.as_view(), name='add-item'),
    path('<int:pk>/<int:item_pk>/remove-item', OrderItemDeleteView.as_view(), name='remove-item'),
    path('charts/', orders_charts, name='charts'),
]

companies/models.py
from django.contrib.auth import get_user_model
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.db.models.signals import pre_delete
from django.dispatch import receiver
from django.urls import reverse_lazy
from django.utils.text import slugify

User = get_user_model()


class Company(models.Model):
    class Meta:
        verbose_name_plural = 'companies'

    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='companies')
    name = models.CharField(max_length=255, unique=True)
    slug = models.SlugField(unique=True)
    description = models.TextField(blank=True)
    address = models.CharField(max_length=255, blank=True)
    phone = models.CharField(max_length=31, help_text='Contact phone number')
    email = models.EmailField(help_text='Contact email')

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super(Company, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse_lazy('companies:dashboard', args=[self.slug])

    def __str__(self):
        return self.name


@receiver(pre_delete, sender=Company)
def delete_company(sender, instance, **kwargs):
    for manager in instance.managers.all():
        user = User.objects.filter(manager=manager).first()
        user.delete()

company/models.py
from django.contrib.auth import get_user_model
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.db.models.signals import post_delete, pre_delete
from django.dispatch import receiver
from django.urls import reverse_lazy

User = get_user_model()


class Company(models.Model):
    class Meta:
        verbose_name_plural = 'company'

    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='companies')
    name = models.CharField(max_length=255)
    description = models.TextField()
    address = models.CharField(max_length=255)
    phone = models.CharField(max_length=31, blank=True, help_text='Contact phone number')
    email = models.EmailField(blank=True, help_text='Contact email')

    def get_absolute_url(self):
        return reverse_lazy('company:detail', args=[self.pk])

    def __str__(self):
        return self.name


class Manager(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='manager')
    company = models.ForeignKey('Company', on_delete=models.CASCADE, related_name='managers')

    def __str__(self):
        return self.user.username


@receiver(pre_delete, sender=Company)
def delete_company(sender, instance, **kwargs):
    managers = Manager.objects.filter(company=instance)
    for manager in managers:
        user = User.objects.filter(manager=manager).first()
        user.delete()

companies/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Fieldset, ButtonHolder, Submit, MultiField, Div
from django import forms
from django.contrib.auth import get_user_model

from companies.models import Company

User = get_user_model()


class CompanyForm(forms.ModelForm):
    class Meta:
        model = Company
        fields = ('name', 'description', 'address', 'email', 'phone',)

    name = forms.CharField(
        required=True,
        help_text='(Required)',
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Name',
            }
        )
    )

    description = forms.CharField(
        max_length=500,
        widget=forms.Textarea(
            attrs={
                'class': 'form-control',
                'placeholder': 'Description',
                'rows': 3
            }
        )
    )

    address = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Address',
            }
        )
    )

    email = forms.EmailField(
        max_length=100,
        required=True,
        help_text='(Required)',
        widget=forms.EmailInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'exapmple@domain.com'
            }
        )
    )
    phone = forms.RegexField(
        required=True,
        regex=r'^\+?1?\d{9,15}$',
        max_length=15,
        help_text='(Required)',
        widget=forms.TextInput(
            attrs={
                'placeholder': '+380999999999',
                'class': 'form-control',
            }
        )
    )

company/forms.py
from django import forms
from django.contrib.auth import get_user_model

from company.models import Company

User = get_user_model()


class CompanyForm(forms.ModelForm):
    class Meta:
        model = Company
        fields = ('name', 'description', 'address', 'email', 'phone',)

    name = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Company name',
                'id': 'name'
            }
        )
    )

    description = forms.CharField(
        widget=forms.Textarea(
            attrs={
                'class': 'form-control',
                'placeholder': 'Company description',
                'id': 'description'
            }
        )
    )

    address = forms.CharField(
        widget=forms.Textarea(
            attrs={
                'class': 'form-control',
                'placeholder': 'Company address',
                'id': 'description'
            }
        )
    )

    email = forms.EmailField(
        max_length=100,
        help_text='Required',
        error_messages={
            'required': 'Sorry, you will need an email'
        },
        widget=forms.EmailInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Email'
            }
        )
    )
    phone = forms.RegexField(
        regex=r'^\+?1?\d{9,15}$',
        error_messages={
            'required': "Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed."
        },
        max_length=15,
        help_text='Required',
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Company phone number',
                'class': 'form-control',
            }
        )
    )

companies/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView, ListView
from companies.forms import CompanyForm
from django.urls import reverse_lazy
from companies.models import Company
from core.mixins import PreviousPageMixin, ModelNameMixin, LinkMixin, PermissionMixin


class CompanyCreateView(PermissionMixin, ModelNameMixin, PreviousPageMixin, CreateView):
    template_name = 'bases/actions/base_add.html'
    form_class = CompanyForm
    model = Company
    success_url = reverse_lazy('accounts:companies')

    def form_valid(self, form):
        company = form.save(commit=False)
        company.user = self.request.user
        company.save()
        return super().form_valid(form)


class CompanyListView(PermissionMixin, ListView):
    template_name = 'companies/company_list.html'
    model = Company
    context_object_name = 'companies'

    def get_queryset(self):
        return Company.objects.filter(user=self.request.user)


class CompanyDetailView(LoginRequiredMixin, LinkMixin, DetailView):
    template_name = 'companies/company_detail.html'
    context_object_name = 'company'
    model = Company


class CompanyUpdateView(PermissionMixin, PreviousPageMixin, UpdateView):
    template_name = 'bases/actions/base_update.html'
    form_class = CompanyForm
    model = Company
    success_url = reverse_lazy('accounts:companies')


class CompanyDeleteView(PermissionMixin, PreviousPageMixin, DeleteView):
    template_name = 'bases/actions/base_delete.html'
    success_url = reverse_lazy('accounts:profile')
    model = Company

company/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView

from accounts.forms import UserRegistrationForm, UserUpdateForm
from company.forms import CompanyForm
from company.mixins import AtomicMixin
from company.models import Company, Manager, User

HTTP_REFERER = None


class CompanyCreationView(CreateView):
    template_name = 'company/company_create.html'
    form_class = CompanyForm
    model = Company
    success_url = reverse_lazy('accounts:profile')

    def form_valid(self, form):
        company = form.save(commit=False)
        company.user = self.request.user
        company.save()
        return super().form_valid(form)


class CompanyDetailView(DetailView):
    template_name = 'company/company_detail.html'
    context_object_name = 'company'
    model = Company


class CompanyUpdateView(UpdateView):
    template_name = 'company/company_update.html'
    form_class = CompanyForm
    model = Company
    success_url = reverse_lazy('accounts:profile')


class CompanyDeleteView(DeleteView):
    template_name = 'company/company_delete.html'
    success_url = reverse_lazy('accounts:profile')
    model = Company


class ManagerCreateView(AtomicMixin, CreateView):
    model = User
    template_name = 'managers/manager_add.html'

    def get_form(self, form_class=UserRegistrationForm):
        form = super(ManagerCreateView, self).get_form(form_class)
        form.fields['companies'].queryset = self.request.user.companies
        return form

    def form_valid(self, form):
        user = form.save(commit=False)
        user.is_leader = False
        user.is_manager = True
        user.save()
        manager = Manager.objects.create(
            user=user,
            company=form.cleaned_data['companies']
        )

        self.success_url = manager.company.get_absolute_url()

        return super().form_valid(form)


class ManagerDeleteView(DeleteView):
    template_name = 'managers/manager_delete.html'
    success_url = reverse_lazy('accounts:profile')
    model = User


class ManagerUpdateView(UpdateView):
    template_name = 'managers/manager_update.html'
    model = User

    def get_form(self, form_class=UserUpdateForm):
        form = super(ManagerUpdateView, self).get_form(form_class)
        form.fields['companies'].queryset = self.request.user.companies
        return form

    def form_valid(self, form):
        user = form.save(commit=False)
        user.is_leader = False
        user.is_manager = True
        user.save()

        manager = Manager.objects.get(user=user)
        manager.company = form.cleaned_data['companies']
        manager.save()

        self.success_url = manager.company.get_absolute_url()

        return super().form_valid(form)

templates/companies/base.html
{% extends 'base.html' %}

{% block content %}
    {% include 'companies/include/header.html' %}
    <div class="container-fluid">
        <div class="row">
            {% include 'companies/include/sidebar.html' %}
            <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
                <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
                    {% block section_header %}

                    {% endblock %}
                </div>
                {% block section_content %}

                {% endblock %}
            </main>
        </div>
    </div>
{% endblock %}

templates/companies/company_customers.html
{% extends 'companies/base.html' %}


{% block section_header %}
    <h1 class="h2">Customers</h1>
    <a href="{% url 'customers:add' company.slug %}" type="button" class="btn btn-sm btn-outline-dark">
        Add customer
    </a>
{% endblock %}

{% block section_content %}
    <div class="table-responsive">
        <table class="table">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Full name</th>
                <th scope="col">Date of birth</th>
                <th scope="col"></th>
            </tr>
            </thead>
            <tbody>
            {% for customer in customers %}
                <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td><a href="{% url 'customers:detail' company.slug customer.pk %}"
                           class="text-decoration-none">{{ customer.get_name }}</a></td>
                    <td>{{ customer.date_of_birth }}</td>
                    <td class="d-flex justify-content-end">
                        <a href="{% url 'customers:update' company.slug customer.pk %}"
                           class="text-decoration-none mx-2">
                            <script>
                                console.log('{{ company.slug }}')
                            </script>
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16"
                                 fill="currentColor"
                                 class="bi bi-pencil-square" viewBox="0 0 16 16">
                                <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"></path>
                                <path fill-rule="evenodd"
                                      d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"></path>
                            </svg>
                        </a>
                        <a href="{% url 'customers:delete' company.slug customer.pk %}"
                           class="text-decoration-none">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16"
                                 fill="currentColor"
                                 class="bi bi-trash text-danger" viewBox="0 0 16 16">
                                <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"></path>
                                <path fill-rule="evenodd"
                                      d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"></path>
                            </svg>
                        </a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

templates/companies/company_detail.html
{% extends 'bases/company_base.html' %}

{% block section_header %}
    <h1 class="h2">Dashboard</h1>
{% endblock %}

{% block section_content %}
    <canvas id="orderChart" data-url="{% url 'companies:orders:charts' company.slug %}"></canvas>

    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>
    <script>

        $(function () {

            var $orderChart = $("#orderChart");
            $.ajax({
                url: $orderChart.data("url"),
                success: function (data) {

                    var ctx = $orderChart[0].getContext("2d");

                    new Chart(ctx, {
                        type: 'bar',
                        data: {
                            labels: data.labels,
                            datasets: [{
                                label: 'Sales amount',
                                backgroundColor: '#007bff',
                                data: data.data
                            }]
                        },
                        options: {
                            responsive: true,
                            legend: {
                                position: 'top',
                            },
                            title: {
                                display: true,
                                text: 'Sales by day',
                            }
                        }
                    });

                }
            });

        });

    </script>
{% endblock %}

templates/companies/company_list.html
{% extends 'bases/base.html' %}

{% block header %}
    {% include 'accounts/include/header.html' %}
{% endblock %}

{% block content %}
    <div class="container">
        <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
            <h1 class="display-4 fw-normal">Companies</h1>
            <p class="fs-5 text-muted">List of the company that is registered to your account in our crm system</p>
            <a class="btn btn-outline-dark" href="{% url 'accounts:companies-add' %}">Add company</a>
        </div>
        <div class="row row-cols-1 row-cols-md-2 g-2">
            {% for company in companies %}
                <div class="col p-5">
                    <div class="d-flex justify-content-between">
                        <h5><a href="{{ company.get_absolute_url }}" class="text-decoration-none text-dark">
                            {{ company.name }}
                        </a></h5>
                        <div>
                            <a href="{% url 'accounts:companies-update' company.slug %}" class="text-decoration-none">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                     class="bi bi-pencil-square" viewBox="0 0 16 16">
                                    <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"></path>
                                    <path fill-rule="evenodd"
                                          d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"></path>
                                </svg>
                                <a href="{% url 'accounts:companies-delete' company.slug %}" class="text-decoration-none">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                         class="bi bi-trash text-danger" viewBox="0 0 16 16">
                                        <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"></path>
                                        <path fill-rule="evenodd"
                                              d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"></path>
                                    </svg>
                                </a>
                            </a>
                        </div>
                    </div>
                    <h6 class="text-muted">Description:</h6>
                    <p>{{ company.description }}</p>
                     <h6 class="text-muted">Company contacts:</h6>
                    <p><span class="fw-bold">Address:</span> {{ company.address }}</p>
                    <p><span class="fw-bold">Email:</span> {{ company.email }}</p>
                    <p><span class="fw-bold">Phone:</span> {{ company.phone }}</p>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/companies/company_managers.html
{% extends 'companies/base.html' %}


{% block section_header %}
    <h1 class="h2">Managers</h1>
    <a href="{% url 'managers:add' company.slug %}" type="button" class="btn btn-sm btn-outline-dark">
        Add manager
    </a>
{% endblock %}

{% block section_content %}
    <div class="table-responsive">
        <table class="table">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Full name</th>
                <th scope="col">Email</th>
                <th scope="col">Phone</th>
                <th scope="col"></th>
            </tr>
            </thead>
            <tbody>
            {% for manager in managers %}
                <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td>{{ manager.user.get_name }}</td>
                    <td>{{ manager.user.email }}</td>
                    <td>{{ manager.user.phone }}</td>
                    <td class="d-flex justify-content-end">
                        <a href="{% url 'managers:update' company.slug manager.user.pk %}"
                           class="text-decoration-none mx-2">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16"
                                 fill="currentColor"
                                 class="bi bi-pencil-square" viewBox="0 0 16 16">
                                <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"></path>
                                <path fill-rule="evenodd"
                                      d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"></path>
                            </svg>
                        </a>
                        <a href="{% url 'managers:delete' company.slug manager.user.pk %}"
                           class="text-decoration-none">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16"
                                 fill="currentColor"
                                 class="bi bi-trash text-danger" viewBox="0 0 16 16">
                                <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"></path>
                                <path fill-rule="evenodd"
                                      d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"></path>
                            </svg>
                        </a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}