accounts/urls.py
from django.contrib.auth.views import (
    LoginView, LogoutView, PasswordResetView,
    PasswordResetConfirmView, PasswordChangeView, PasswordResetDoneView
)
from accounts.forms import UserPasswordResetForm, UserPasswordResetConfirmForm, UserPasswordChangeForm, UserLoginForm
from accounts.views import UserProfileView, activate, UserRegistrationView, UserUpdateView, UserDeleteView
from django.urls import path
from companies.views import CompanyListView, CompanyCreateView, CompanyUpdateView, CompanyDeleteView
from managers.views import ManagerListView

app_name = 'accounts'

urlpatterns = [
    path('login/',
         LoginView.as_view(
             template_name='registration/login.html',
             authentication_form=UserLoginForm),
         name='login'),

    path('logout/',
         LogoutView.as_view(
             template_name='registration/logout.html'),
         name='logout'),

    path('password_reset/',
         PasswordResetView.as_view(
             template_name='registration/password_reset_form.html',
             form_class=UserPasswordResetForm,),
         name='password_reset'),

    path('password_reset_confirm/<uidb64>/<token>',
         PasswordResetConfirmView.as_view(
             template_name='registration/password_reset_confirm.html',
             form_class=UserPasswordResetConfirmForm),
         name='password_reset_confirm'),

    path('password_change/',
         PasswordChangeView.as_view(
             template_name="registration/password_change_form.html",
             form_class=UserPasswordChangeForm),
         name='password_change'),

    path('activate/<uidb64>/<token>/', activate, name='activate'),
    path('registration/', UserRegistrationView.as_view(), name='registration'),

    path('profile/', UserProfileView.as_view(), name='profile'),
    path('profile/update/<int:pk>/', UserUpdateView.as_view(), name='profile-update'),
    path('profile/delete/<int:pk>/', UserDeleteView.as_view(), name='profile-delete'),

    path('profile/companies/', CompanyListView.as_view(), name='companies'),
    path('profile/managers/', ManagerListView.as_view(template_name='managers/manager_list.html'), name='managers'),
    path('profile/companies/add/', CompanyCreateView.as_view(), name='companies-add'),
    path('profile/companies/update/<slug:slug>/', CompanyUpdateView.as_view(), name='companies-update'),
    path('profile/companies/delete/<slug:slug>/', CompanyDeleteView.as_view(), name='companies-delete'),
]

core/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.contrib.staticfiles.storage import staticfiles_storage
from django.urls import path, include
from django.views.generic import RedirectView

from core.views import LandingView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('<slug:slug>/', include('companies.urls', namespace='companies')),
    path('', LandingView.as_view(), name='landing'),
    path(
        'favicon.ico',
        RedirectView.as_view(url=staticfiles_storage.url('favicon.ico')),
    ),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.contrib.auth.hashers import make_password
from django.contrib.auth.models import AbstractUser, PermissionsMixin
from django.core.mail import send_mail
from django.db import models
from imagekit.processors import ResizeToFill
from imagekit.models import ImageSpecField


def user_directory_path(instance, filename):
    return f'users/avatars/{instance}/{filename}'


class CustomAccountManager(BaseUserManager):

    def create_user(self, email, password, **other_fields):
        if not email:
            raise ValueError('You must provide an email address')

        email = self.normalize_email(email)
        user = self.model(email=email, **other_fields)
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, email, password, **other_fields):
        other_fields.setdefault('is_staff', True)
        other_fields.setdefault('is_superuser', True)
        other_fields.setdefault('is_active', True)

        if other_fields.get('is_staff') is not True:
            raise ValueError('Superuser must be assigned to is_staff=True')
        if other_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must be assigned to is_superuser=True')
        if other_fields.get('is_active') is not True:
            raise ValueError('Superuser must be assigned to is_active=True')

        return self.create_user(email, password, **other_fields)


class BasicUser(PermissionsMixin, AbstractBaseUser):
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)

    is_director = models.BooleanField(default=False)
    is_manager = models.BooleanField(default=False)

    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)

    email = models.EmailField(unique=True)
    phone = models.CharField(max_length=31, unique=True)

    date_of_birth = models.DateTimeField(blank=True, null=True)
    about = models.TextField(max_length=500, blank=True)

    avatar = models.ImageField(upload_to=user_directory_path, default='default.png')
    medium_avatar = ImageSpecField(
        source='avatar',
        processors=[ResizeToFill(256, 256)],
        format='JPEG',
        options={'quality': 90}
    )
    small_avatar = ImageSpecField(
        source='avatar',
        processors=[ResizeToFill(32, 32)],
        format='JPEG',
        options={'quality': 90})

    objects = CustomAccountManager()

    USERNAME_FIELD = 'email'

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

    def get_name(self):
        return f'{self.first_name} {self.last_name}'

    def email_user(self, subject, message, from_email=None, **kwargs):
        send_mail(subject, message, from_email, [self.email], **kwargs)

    def save(self, *args, **kwargs):
        if not self.id and not self.is_staff and not self.is_superuser:
            self.password = make_password(self.password)
        super().save(*args, **kwargs)

accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm, PasswordResetForm, SetPasswordForm, PasswordChangeForm

from companies.models import Company

User = get_user_model()


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'id': 'login-username'
        }
    ))
    password = forms.CharField(widget=forms.PasswordInput(
        attrs={
            'class': 'form-control',
            'id': 'login-password'
        }
    ))


class UserRegistrationForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email', 'phone', 'about', 'avatar')

    first_name = forms.CharField(
        label='Enter first name',
        min_length=4, max_length=50,
        help_text='(Required)',
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'First name'
            }
        )
    )

    last_name = forms.CharField(
        label='Enter last name',
        min_length=4, max_length=50,
        help_text='(Required)',
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Last name'
            }
        )
    )

    email = forms.EmailField(
        max_length=100,
        help_text='(Required)',
        widget=forms.EmailInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Email'
            }
        )
    )

    password = forms.CharField(
        label='Enter password',
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Password'
            }
        )
    )
    password2 = forms.CharField(
        label='Repeat password',
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Repeat password'
            }
        )
    )

    phone = forms.RegexField(
        label='Phone number',
        regex=r'^\+?1?\d{9,15}$',
        max_length=15,
        help_text='(Required)',
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
            }
        )
    )

    about = forms.CharField(
        required=False,
        label='About you',
        max_length=500,
        widget=forms.Textarea(
            attrs={
                'class': 'form-control',
                'placeholder': 'About you',
                'id': 'bio'
            }
        )
    )

    avatar = forms.FileField(
        required=False,
        widget=forms.FileInput(
            attrs={
                'class': 'form-control',
                'id': 'avatar'
            }
        )
    )

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Password do not match.')
        return cd['password2']

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError('Please use another Email, that is already taken.')
        return email


class UserPasswordResetForm(PasswordResetForm):
    email = forms.EmailField(
        max_length=100,
        help_text='(Required)',
        widget=forms.EmailInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'exapmple@domain.com'
            }
        )
    )

    def clean_email(self):
        email = self.cleaned_data['email']
        test = User.objects.filter(email=email)
        if not test:
            raise forms.ValidationError('Unfortunately we can not find that email address')
        return email


class UserPasswordResetConfirmForm(SetPasswordForm):
    new_password1 = forms.CharField(
        label='Password',
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Password',
            }
        )
    )
    new_password2 = forms.CharField(
        label='Repeat password',
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Repeat password',
            }
        )
    )


class UserPasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(
        label='Password',
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Password',
            }
        )
    )
    new_password1 = forms.CharField(
        label='New password',
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Password',
            }
        )
    )
    new_password2 = forms.CharField(
        label='Repeat password',
        widget=forms.PasswordInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Repeat password',
            }
        )
    )


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'phone', 'about', 'avatar']

    first_name = forms.CharField(
        min_length=4, max_length=50,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'First name'
            }
        )
    )

    last_name = forms.CharField(
        min_length=4, max_length=50,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Last name'
            }
        )
    )

    email = forms.EmailField(
        max_length=100,
        widget=forms.EmailInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'exapmple@domain.com'
            }
        )
    )

    phone = forms.RegexField(
        label='Phone number',
        regex=r'^\+?1?\d{9,15}$',
        max_length=15,
        widget=forms.TextInput(
            attrs={
                'placeholder': '+38(099)-999-99-99',
                'class': 'form-control',
            }
        )
    )

    about = forms.CharField(
        required=False,
        label='About you',
        widget=forms.Textarea(
            attrs={
                'class': 'form-control',
                'placeholder': 'About you',
                'id': 'bio'
            }
        )
    )

    avatar = forms.FileField(
        required=False,
        widget=forms.FileInput(
            attrs={
                'class': 'form-control',
                'id': 'avatar'
            }
        )
    )

accounts/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.views.generic import TemplateView, FormView, UpdateView, DeleteView
from accounts.forms import UserRegistrationForm, UserUpdateForm
from django.contrib.auth import get_user_model, login
from django.urls import reverse_lazy
from django.shortcuts import render, redirect
from accounts.token import account_activation_token
from core.mixins import PreviousPageMixin

User = get_user_model()


class UserProfileView(LoginRequiredMixin, TemplateView):
    template_name = 'accounts/profile_detail.html'


class UserRegistrationView(FormView):
    template_name = 'registration/registration.html'
    form_class = UserRegistrationForm
    success_url = reverse_lazy('accounts:profile')

    def form_valid(self, form):
        user = form.save(commit=False)
        user.set_password(form.cleaned_data['password'])
        user.is_director = True
        user.is_active = False
        user.save()
        current_site = get_current_site(self.request)
        subject = 'Activate your account'
        message = render_to_string('registration/account_activation_email.html', {
            'user': user,
            'domain': current_site.domain,
            'uid': urlsafe_base64_encode(force_bytes(user.pk)),
            'token': account_activation_token.make_token(user),
        })
        user.email_user(subject=subject, message=message)
        return super().form_valid(form)


class UserUpdateView(LoginRequiredMixin, PreviousPageMixin, UpdateView):
    template_name = 'bases/actions/base_update.html'
    form_class = UserUpdateForm
    model = User
    success_url = reverse_lazy('accounts:profile')


class UserDeleteView(LoginRequiredMixin, PreviousPageMixin, DeleteView):
    template_name = 'bases/actions/base_delete.html'
    success_url = reverse_lazy('landing')
    model = User


def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user)
        return redirect(reverse_lazy('accounts:login'))
    else:
        return render(request, 'registration/activation_invalid.html')

templates/accounts/profile.html
{% extends 'base.html' %}

{% block header %}
    {% include 'include/header.html' %}
{% endblock %}

{% block content %}
    <div class="container">
        <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
            <h1 class="display-4 fw-normal">Companies</h1>
            <p class="fs-5 text-muted">List of the company that is registered to your account in our crm system</p>
            <a class="btn btn-outline-dark" href="{% url 'company:add' %}">Add company</a>
        </div>
        <div class="row row-cols-1 row-cols-md-2 g-2">
            {% for company in companies %}
                <div class="col p-5">
                    <div class="d-flex justify-content-between">
                        <h5><a href="{{ company.get_absolute_url }}" class="text-decoration-none text-dark">
                            {{ company.name }}
                        </a></h5>
                        <div>
                            <a href="{% url 'company:update' company.pk %}" class="text-decoration-none">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                     class="bi bi-pencil-square" viewBox="0 0 16 16">
                                    <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"></path>
                                    <path fill-rule="evenodd"
                                          d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"></path>
                                </svg>
                                <a href="{% url 'company:delete' company.pk %}" class="text-decoration-none">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                         class="bi bi-trash text-danger" viewBox="0 0 16 16">
                                        <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"></path>
                                        <path fill-rule="evenodd"
                                              d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"></path>
                                    </svg>
                                </a>
                            </a>
                        </div>
                    </div>
                    <h6 class="text-muted">Description</h6>
                    <p>{{ company.description }}</p>
                    <h5 class="">Company contact</h5>
                    <p><span class="fw-bold">Address:</span> {{ company.address }}</p>
                    <p><span class="fw-bold">Email:</span> {{ company.email }}</p>
                    <p><span class="fw-bold">Phone:</span> {{ company.phone }}</p>
                </div>
            {% endfor %}
        </div>

{% endblock %}

templates/accounts/profile_detail.html
{% extends 'bases/base.html' %}


{% if request.user.is_director %}
    {% block header %}
        {% include 'accounts/include/header.html' %}
    {% endblock %}
{% endif %}

{% block content %}
    <div class="container">
        <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
            <h1 class="display-4 fw-normal">Profile</h1>
            <p class="fs-5 text-muted">Here you can view your profile information</p>
        </div>
        <div class="d-flex justify-content-between">
            {% with request.user as user %}
                <div class="col-6 p-5">
                    <div class="d-flex">
                        <h5>{{ user }}</h5>
                        <div class="px-2">
                            <a href="{% url 'accounts:profile-update' user.pk %}" class="text-decoration-none">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                     class="bi bi-pencil-square" viewBox="0 0 16 16">
                                    <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"></path>
                                    <path fill-rule="evenodd"
                                          d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"></path>
                                </svg>
                            </a>
                            <a href="{% url 'accounts:profile-delete' user.pk %}"
                               class="text-decoration-none">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16"
                                     fill="currentColor"
                                     class="bi bi-trash text-danger" viewBox="0 0 16 16">
                                    <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"></path>
                                    <path fill-rule="evenodd"
                                          d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"></path>
                                </svg>
                            </a>
                        </div>
                    </div>
                    {% if request.user.is_manager %}
                        <p class="mt-2"><span class="text-muted h6">Company:</span>
                            <a class="text-decoration-none" href="{{ user.manager.company.get_absolute_url }}">
                                {{ user.manager.company }}
                            </a>
                        </p>
                    {% endif %}
                    {% if user.about %}
                        <h6 class="text-muted">About you:</h6>
                        <p>{{ user.about }}</p>
                    {% endif %}
                    <h6 class="text-muted">Contacts:</h6>
                    <p><span class="fw-bold">Email:</span> {{ user.email }}</p>
                    <p><span class="fw-bold">Phone:</span> {{ user.phone }}</p>
                </div>
                <div class="p-5">
                    <img src="{{ user.medium_avatar.url }}" alt="avatar">
                </div>
            {% endwith %}
        </div>
    </div>
{% endblock %}

templates/accounts/update.html
{% extends 'registration/base.html' %}


{% block section %}
    <a class="small text-decoration-none" href="{% url "accounts:profile" %}">Back to Dashboard</a>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}

        {% if form.errors %}
            <p>Please correct the following errors:</p>
            {% for field in form %}
                {% if field.errors %}
                    <div class="alert alert-primary" role="alert">
                        {{ field.label }}: {{ field.errors|striptags }}
                    </div>
                {% endif %}
            {% endfor %}
        {% endif %}

        <div class="mb-3">
            <label class="small fw-bold">
                {{ form.username.label }}
                <span class="text-muted">(Required)</span>
            </label>
            {{ form.username }}
        </div>

        <div class="mb-3">
            <label class="small fw-bold">
                {{ form.first_name.label }}
                <span class="text-muted">(Required)</span>
            </label>
            {{ form.first_name }}
        </div>

        <div class="mb-3">
            <label class="small fw-bold">
                {{ form.last_name.label }}
                <span class="text-muted">(Required)</span>
            </label>
            {{ form.last_name }}
        </div>

        <div class="mb-3">
            <label class="small fw-bold">
                {{ form.email.label }}
                <span class="text-muted">(Required)</span>
            </label>
            {{ form.email }}
        </div>

        <div class="mb-3">
            <lable class="small fw-bold">{{ form.phone.label }}</lable>
            <span class="text-muted">(Required)</span>
            {{ form.phone }}
        </div>

        <div class="mb-3">
            <lable class="small fw-bold">{{ form.bio.label }}</lable>
            <span class="text-muted">(Required)</span>
            {{ form.bio }}
        </div>

        <div class="mb-3">
            <lable class="small fw-bold">{{ form.avatar.label }}</lable>
            {{ form.avatar }}
        </div>

        <div class="d-grid gap-2">
            <button class="btn btn-dark btn-block py-2 fw-bold" type="submit" value="Log In">
                Submit
            </button>
        </div>
    </form>
{% endblock %}