accounts/urls.py
from django.contrib.auth.views import (
    LoginView, LogoutView, PasswordResetView,
    PasswordResetConfirmView, PasswordChangeView, PasswordResetDoneView
)
from accounts.forms import UserPasswordResetForm, UserPasswordResetConfirmForm, UserPasswordChangeForm, UserLoginForm
from accounts.views import UserProfileView, activate, UserRegistrationView, UserUpdateView, UserDeleteView
from django.urls import path
from companies.views import CompanyListView, CompanyCreateView, CompanyUpdateView, CompanyDeleteView
from managers.views import ManagerListView

app_name = 'accounts'

urlpatterns = [
    path('login/',
         LoginView.as_view(
             template_name='registration/login.html',
             authentication_form=UserLoginForm),
         name='login'),

    path('logout/',
         LogoutView.as_view(
             template_name='registration/logout.html'),
         name='logout'),

    path('password_reset/',
         PasswordResetView.as_view(
             template_name='registration/password_reset_form.html',
             form_class=UserPasswordResetForm,),
         name='password_reset'),

    path('password_reset_confirm/<uidb64>/<token>',
         PasswordResetConfirmView.as_view(
             template_name='registration/password_reset_confirm.html',
             form_class=UserPasswordResetConfirmForm),
         name='password_reset_confirm'),

    path('password_change/',
         PasswordChangeView.as_view(
             template_name="registration/password_change_form.html",
             form_class=UserPasswordChangeForm),
         name='password_change'),

    path('activate/<uidb64>/<token>/', activate, name='activate'),
    path('registration/', UserRegistrationView.as_view(), name='registration'),

    path('profile/', UserProfileView.as_view(), name='profile'),
    path('profile/update/<int:pk>/', UserUpdateView.as_view(), name='profile-update'),
    path('profile/delete/<int:pk>/', UserDeleteView.as_view(), name='profile-delete'),

    path('profile/companies/', CompanyListView.as_view(), name='companies'),
    path('profile/managers/', ManagerListView.as_view(template_name='managers/manager_list.html'), name='managers'),
    path('profile/companies/add/', CompanyCreateView.as_view(), name='companies-add'),
    path('profile/companies/update/<slug:slug>/', CompanyUpdateView.as_view(), name='companies-update'),
    path('profile/companies/delete/<slug:slug>/', CompanyDeleteView.as_view(), name='companies-delete'),
]

core/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.contrib.staticfiles.storage import staticfiles_storage
from django.urls import path, include
from django.views.generic import RedirectView

from core.views import LandingView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('<slug:slug>/', include('companies.urls', namespace='companies')),
    path('', LandingView.as_view(), name='landing'),
    path(
        'favicon.ico',
        RedirectView.as_view(url=staticfiles_storage.url('favicon.ico')),
    ),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/include/header.html
<header class="p-3 mb-3 border-bottom">
    <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
            <a href="{% url 'accounts:profile' %}"
               class="d-flex align-items-center mb-2 mb-lg-0 text-dark text-decoration-none">
                <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor"
                     class="bi bi-laptop-fill" viewBox="0 0 16 16">
                    <path d="M2.5 2A1.5 1.5 0 0 0 1 3.5V12h14V3.5A1.5 1.5 0 0 0 13.5 2h-11zM0 12.5h16a1.5 1.5 0 0 1-1.5 1.5h-13A1.5 1.5 0 0 1 0 12.5z"/>
                </svg>
            </a>

            <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
            </ul>

            <div class="dropdown text-end">
                <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle" id="dropdownUser1"
                   data-bs-toggle="dropdown" aria-expanded="false">
                    <img src="{{ request.user.avatar.url }}" alt="mdo" width="32" height="32" class="rounded-circle">
                </a>
                <ul class="dropdown-menu text-small" aria-labelledby="dropdownUser1">
                    <li><a class="dropdown-item" href="{% url 'accounts:password-change' %}">Change password</a></li>
                    <li>
                        <a class="dropdown-item" href="{% url 'accounts:profile-update' request.user.id %}">
                            Update profile
                        </a>
                    </li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>
                    <li><a class="dropdown-item" href="{% url 'accounts:logout' %}">Sign out</a></li>
                </ul>
            </div>
        </div>
    </div>
</header>

templates/include/scripts.html
<script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk="
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js"
        integrity="sha384-SR1sx49pcuLnqZUnnPwx6FCym0wLsk5JZuNx2bPPENzswTNFaQU1RDvt3wT4gWFG"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js"
        integrity="sha384-j0CNLUeiqtyaRmlzUHCPZ+Gy5fQu0dQ6eZ/xAww941Ai1SxSY+0EQqNXNE6DZiVc"
        crossorigin="anonymous"></script>
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.24/js/jquery.dataTables.js"></script>

templates/include/styles.html
{% load static %}

<link rel="stylesheet" href="{% static 'css/style.css' %}">
<link rel="stylesheet" href="{% static 'css/dashboard.css' %}">
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.24/css/jquery.dataTables.css">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
      integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">