accounts/urls.py
from django.contrib.auth.views import (
    LoginView, LogoutView, PasswordResetView,
    PasswordResetConfirmView, PasswordChangeView, PasswordResetDoneView
)
from accounts.forms import UserPasswordResetForm, UserPasswordResetConfirmForm, UserPasswordChangeForm, UserLoginForm
from accounts.views import UserProfileView, activate, UserRegistrationView, UserUpdateView, UserDeleteView
from django.urls import path
from companies.views import CompanyListView, CompanyCreateView, CompanyUpdateView, CompanyDeleteView
from managers.views import ManagerListView

app_name = 'accounts'

urlpatterns = [
    path('login/',
         LoginView.as_view(
             template_name='registration/login.html',
             authentication_form=UserLoginForm),
         name='login'),

    path('logout/',
         LogoutView.as_view(
             template_name='registration/logout.html'),
         name='logout'),

    path('password_reset/',
         PasswordResetView.as_view(
             template_name='registration/password_reset_form.html',
             form_class=UserPasswordResetForm,),
         name='password_reset'),

    path('password_reset_confirm/<uidb64>/<token>',
         PasswordResetConfirmView.as_view(
             template_name='registration/password_reset_confirm.html',
             form_class=UserPasswordResetConfirmForm),
         name='password_reset_confirm'),

    path('password_change/',
         PasswordChangeView.as_view(
             template_name="registration/password_change_form.html",
             form_class=UserPasswordChangeForm),
         name='password_change'),

    path('activate/<uidb64>/<token>/', activate, name='activate'),
    path('registration/', UserRegistrationView.as_view(), name='registration'),

    path('profile/', UserProfileView.as_view(), name='profile'),
    path('profile/update/<int:pk>/', UserUpdateView.as_view(), name='profile-update'),
    path('profile/delete/<int:pk>/', UserDeleteView.as_view(), name='profile-delete'),

    path('profile/companies/', CompanyListView.as_view(), name='companies'),
    path('profile/managers/', ManagerListView.as_view(template_name='managers/manager_list.html'), name='managers'),
    path('profile/companies/add/', CompanyCreateView.as_view(), name='companies-add'),
    path('profile/companies/update/<slug:slug>/', CompanyUpdateView.as_view(), name='companies-update'),
    path('profile/companies/delete/<slug:slug>/', CompanyDeleteView.as_view(), name='companies-delete'),
]

core/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.contrib.staticfiles.storage import staticfiles_storage
from django.urls import path, include
from django.views.generic import RedirectView

from core.views import LandingView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('<slug:slug>/', include('companies.urls', namespace='companies')),
    path('', LandingView.as_view(), name='landing'),
    path(
        'favicon.ico',
        RedirectView.as_view(url=staticfiles_storage.url('favicon.ico')),
    ),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/landing.html
{% extends 'bases/base.html' %}
{% block content %}
    <style>
        .fill-height {
            position: relative;
            min-height: 100%;
            height: 100vh;
        }

        #hello {
            position: absolute;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
            font-weight: bold
        }

        #hello h1, p, a {
            text-align: center;
        }


    </style>
    {% if request.user.is_authenticated %}
        <script>
            window.location.href = '{% url 'accounts:profile' %}'
        </script>
    {% endif %}
    <div class="container-fluid fill-height ">
        <div class="row">
            <div class="col-lg-1"></div>
            <div id="hello" class="col-lg-10">
                <div class="d-flex justify-content-center">
                    <svg xmlns="http://www.w3.org/2000/svg" width="128" height="128" fill="currentColor"
                         class="bi bi-laptop-fill mb-5" viewBox="0 0 16 16">
                        <path d="M2.5 2A1.5 1.5 0 0 0 1 3.5V12h14V3.5A1.5 1.5 0 0 0 13.5 2h-11zM0 12.5h16a1.5 1.5 0 0 1-1.5 1.5h-13A1.5 1.5 0 0 1 0 12.5z"></path>
                    </svg>
                </div>
                <h1>UCRM</h1>
                <p>This CRM helps you manage your leads.</p>
                <div class="d-flex justify-content-center">
                    <a href="{% url 'accounts:login' %}"
                       class="btn btn-outline-dark">
                        Login to get started
                    </a>
                </div>
            </div>
            <div class="col-lg-1"></div>
        </div>
    </div>
{% endblock %}

templates/test.html
<form method="post" >
    {% csrf_token %}

    {{ form }}
    <button type="submit">Submit</button>
</form>